"""
Configuration globale du jeu Sprout Island.
Contient toutes les constantes pour l'équilibrage du gameplay.
"""

# === LIMITES DES JAUGES ===
SATIETY_MAX = 100
HYDRATION_MAX = 100
ENERGY_MAX = 100
SATIETY_MIN = 0
HYDRATION_MIN = 0
ENERGY_MIN = 0

# === PERTES QUOTIDIENNES AUTOMATIQUES ===
DAILY_SATIETY_LOSS = 12
DAILY_HYDRATION_LOSS = 15
DAILY_ENERGY_LOSS = 8

# === ACTIONS DE BASE ===
FISH_SATIETY_GAIN = 35
FISH_ENERGY_LOSS = 15

DRINK_HYDRATION_GAIN = 40
DRINK_ENERGY_LOSS = 10

SLEEP_ENERGY_GAIN = 70

EXPLORE_ENERGY_LOSS = 20

# === ÉVÉNEMENTS ALÉATOIRES ===
RAIN_HYDRATION_GAIN = 35
RAIN_DURATION = 3

ANIMAL_FLEE_ENERGY_LOSS = 30

ANIMAL_HUNT_ENERGY_LOSS = 40
ANIMAL_HUNT_SATIETY_GAIN = 55

FRUIT_SATIETY_GAIN = 20
FRUIT_HYDRATION_GAIN = 15

HEATWAVE_HYDRATION_LOSS = 25
HEATWAVE_ENERGY_LOSS = 15
HEATWAVE_DURATION = 3
HEATWAVE_DAILY_HYDRATION_PENALTY = 10

# === CONDITIONS DE VICTOIRE ===
DAYS_TO_WIN = 20
