"""
Configuration globale du jeu Sprout Island.
Contient toutes les constantes pour l'équilibrage du gameplay.
"""
SATIETY_MAX = 100
HYDRATION_MAX = 100
ENERGY_MAX = 100
SATIETY_MIN = 0
HYDRATION_MIN = 0
ENERGY_MIN = 0

DAILY_SATIETY_LOSS = 5
DAILY_HYDRATION_LOSS = 5
DAILY_ENERGY_LOSS = 5

SATIETY_GAIN = 25
HYDRATION_GAIN = 30
ENERGY_GAIN = 50

SATIETY_LOSS = 10
HYDRATION_LOSS = 15
ENERGY_LOSS = 20

ANIMAL_FLEE_ENERGY_LOSS = 30
ANIMAL_HUNT_ENERGY_LOSS = 50
ANIMAL_HUNT_SATIETY_GAIN = 70

DAYS_TO_WIN = 20
